### PR TITLE
fix: use the CF_TORCH_CUDA_ARCH_LIST set by pytorch activation

### LINKED ISSUE #154: Running the `linux-aarch64` build for an Jetson Orin Nano
I've build the [PR](https://github.com/conda-forge/torchvision-feedstock/pull/151) to get tegra support on `torchvision`. While testing I didn't go deep enough.

I'm still getting this issue:
```
  File "/home/ruben/pytorch-jetson/.pixi/envs/default/lib/python3.14/site-packages/torchvision/ops/boxes.py", line 102, in _batched_nms_coordinate_trick
    keep = nms(boxes_for_nms, scores, iou_threshold)
  File "/home/ruben/pytorch-jetson/.pixi/envs/default/lib/python3.14/site-packages/torchvision/ops/boxes.py", line 48, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/pytorch-jetson/.pixi/envs/default/lib/python3.14/site-packages/torch/_ops.py", line 1209, in __call__
    return self._op(*args, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
Search for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

When researching this a little bit more it showed that I should add the `8.7` TORCH_CUDA_ARCH to this line:
https://github.com/conda-forge/torchvision-feedstock/blob/5783ee4349cc77c98e8dced6b92f9f92c71846a2/recipe/build.sh#L9

After rebuilding that it solved the issue. Now I found that pytorch indeed add that target:
https://github.com/conda-forge/pytorch-cpu-feedstock/blob/cdeaf5ae3973f89d8e758ff05a469441a29b1722/recipe/build.sh#L234

Should we add the same configuration to the build script of `torchvision`?

### PR DESCRIPTION
**Pull request by ruben-arts**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR changes that `torchvision`'s build script sets the `TORCH_CUDA_ARCH_LIST` variable for compilation and uses the one set by the `pytorch` package's activation script. This way the two will not be out of sync, as what happened through the [PR](https://github.com/conda-forge/torchvision-feedstock/pull/151) I made.

Related but not fixed: #154 
We should do another pass when pytorch has the fixes in.

### CODE REVIEW

**Comment by ruben-arts** [comment]
Testing wheter changing the cuda arch from `10.1` to `11.0` will work while it's not changed in the pytorch feedstock: [`2fdb011` (this PR)](https://github.com/conda-forge/torchvision-feedstock/pull/155/commits/2fdb0118f1e57939605f0f201312940f46e79bd7)

**Comment by ruben-arts** [comment]
@carterbox or @traversaro have you seen this type of issue before: https://github.com/conda-forge/torchvision-feedstock/actions/runs/23584972545/job/68675843661?pr=155#step:3:1697

**Comment by traversaro** [comment]
> @carterbox or @traversaro have you seen this type of issue before: https://github.com/conda-forge/torchvision-feedstock/actions/runs/23584972545/job/68675843661?pr=155#step:3:1697

The error is:

~~~
[91](https://github.com/conda-forge/torchvision-feedstock/actions/runs/23584972545/job/68675843661?pr=155#step:3:1696)
 │ │   nvcc warning : incompatible redefinition for option 'compiler-bindir', the last value of this option was used
 │ │   nvcc fatal   : Unsupported gpu architecture 'compute_110'
 │ │   error: command '$BUILD_PREFIX/bin/nvcc' failed with exit code 1
 │ │   error: subprocess-exited-with-error
~~~

it is an expected error, in CUDA 12.9 10.1 is a recognized architecture, while 11.0 no (as it is a  CUDA 13+ only arch).

**Comment by traversaro** [comment]
While we wait for reaching a consensus in https://github.com/conda-forge/pytorch-cpu-feedstock/issues/494, I think the easiest fix here is to keep to use `export TORCH_CUDA_ARCH_LIST="${CF_TORCH_CUDA_ARCH_LIST}`, except on Tegra, were we should set `TORCH_CUDA_ARCH_LIST` to `8.7+PTX`.

**Comment by traversaro** [comment]
Alternatively, if we do really want to build for 10.1, we can patch https://github.com/pytorch/pytorch/blob/f250f024a41f6f3a818dee0f57913b3a62275150/torch/utils/cpp_extension.py#L4 on the fly, even if it is not a file installed here. The patch will be lost after the build, but it should permit to build torchvision fine, we do something similar in https://github.com/conda-forge/llama.cpp-feedstock/blob/36b4d5b83b567717db33e3c055b2e8e4af52ae3f/recipe/recipe.yaml#L28-L43 .

File: recipe/build.sh [hunk 1]
```diff
@@ -5,15 +5,21 @@ if [[ "$cuda_compiler_version" == "None" ]]; then
...
-      echo "unsupported cuda version. edit build.sh"
+    # CF_TORCH_CUDA_ARCH_LIST is set by pytorch's activation scripts to match the arch list pytorch was built with.
+    # See https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/activate.sh
+    if [[ -z "${CF_TORCH_CUDA_ARCH_LIST:-}" ]]; then
+      echo "CF_TORCH_CUDA_ARCH_LIST is not set. Ensure the correct pytorch is installed and its activation scripts have run."
       exit 1
+    fi
+    # Due to a change in the supported CUDA architectures, we need to replace 10.1 with 11.0 in the arch list if it is present.
+    # See: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/494
+    export TORCH_CUDA_ARCH_LIST="${CF_TORCH_CUDA_ARCH_LIST//10.1/11.0}"
```
Comment (traversaro) [inline recipe/build.sh]: Can you remove the 10.1/11.0 workaround as it is not useful anymore now that we have the tegra if?

Comment (ruben-arts) [reply recipe/build.sh]: Yes, done in: [`54baa4b` (this PR)](https://github.com/conda-forge/torchvision-feedstock/pull/155/commits/54baa4b6c099e5a281240d993dccf41b7a3c2f3d)

**Comment by ruben-arts** [comment]
There is still an issue with the Windows build if we use the CF_TORCH_CUDA_ARCH_LIST var as the `libpytorch` windows packages contain an empty file in the activation scripts folder. @wolfv is looking into improving that. 

To unblock this PR I reverted the change for windows: [`ad66f82` (this PR)](https://github.com/conda-forge/torchvision-feedstock/pull/155/commits/ad66f8299c531629e18828c0c7126fedcbcc1c34)

**Comment by ruben-arts** [comment]
The fix that should help with also making this environment var trick work on windows: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/495

**Comment by ruben-arts** [comment]
@carterbox @hmaarrfk @traversaro This PR is in a mergeble state. It will unblock futher testing.

What we should still do:
- Fix the windows script when https://github.com/conda-forge/pytorch-cpu-feedstock/pull/495 is merged
- Fix the tegra script when `pytroch-cpu` supports this proposal by @traversaro https://github.com/conda-forge/pytorch-cpu-feedstock/issues/494#issuecomment-4151089725

File: recipe/build.bat [hunk 2]
```diff
@@ -19,7 +19,7 @@ if not "%cuda_compiler_version%" == "None" (
         echo "unsupported cuda version. edit build.bat"
         exit /b 1
     )
-
+
```
Comment (traversaro) [inline recipe/build.bat]: I guess this change can be removed?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Good to go for me, modulo removing the trailing whitespace in bld.bat

File: recipe/build.bat (hunk 2 above)
Comment (ruben-arts) [inline recipe/build.bat]:
```suggestion

```

Comment (ruben-arts) [reply recipe/build.bat]: Yep

File: recipe/build.sh [hunk 3]
```diff
@@ -5,15 +5,21 @@ if [[ "$cuda_compiler_version" == "None" ]]; then
...
 else
   export CUDA_TOOLKIT_ROOT_DIR="${PREFIX}"
-  if [[ ${cuda_compiler_version} == 12.9 ]]; then
-      export TORCH_CUDA_ARCH_LIST="5.0;6.0;7.0;7.5;8.0;8.6;8.9;9.0;10.0;12.0+PTX"
-      export CUDA_TOOLKIT_ROOT_DIR="${PREFIX}"
-  elif [[ ${cuda_compiler_version} == 13.0 ]]; then
-      export TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6;8.9;9.0;10.0;11.0;12.0+PTX"
+  if [[ "${arm_variant_type:-}" == "tegra" ]]; then
+    # Tegra (Jetson) devices only support sm_87, so we hardcode the arch list.
+    export TORCH_CUDA_ARCH_LIST="8.7+PTX"
```
Comment (hmaarrfk) [inline recipe/build.sh:10]: is this supposed to be a new build? no new `.ci_support` files have been added.

Comment (ruben-arts) [reply recipe/build.sh:10]: The existing tegra builds need to rebuild but that should already work out. They where incorrectly building before with that long `TORCH_CUDA_ARCH_LIST`.

**Comment by hmaarrfk** [comment]
Can you add yourself as a maintainer, along with an inline comment that you are particularly interested in tegra support. 

This will help us keep this package alive in the long run.

**Comment by ruben-arts** [comment]
@hmaarrfk Thanks for the invite, I added myself as maintainer.

**Comment by ruben-arts** [comment]
@hmaarrfk I think the CI failure on osx is just a flacky timeout. The previous run worked.

**Comment by ruben-arts** [comment]
Friendly ping for @hmaarrfk @h-vetinari @nehaljwani

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender
